- name: Install IIS
  hosts: Windows
  gather_facts: true
  tasks:
    - name: Install IIS
      win_feature:
        name: "Web-Server"
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes
        
    - name: Download simple web site to 'C:\inetpub\wwwroot\index.html'
      win_get_url:
        url: 'https://raw.githubusercontent.com/thisdavejohnson/mywebapp/master/index.html'
        dest: 'C:\inetpub\wwwroot\index.html'
    
    - name: Deploy the project on apache
      win_copy:
        dest: 'C:\inetpub\wwwroot\index.html'
        content: "<h1> F5 LTM-1 - Deployed by Ansible Tower on {{ansible_hostname}} </h1>"
    
